sudo apt-get update
sudo apt-get install git-core
sudo apt-get install gnupg
sudo apt-get install flex
sudo apt-get install bison
sudo apt-get install python
sudo apt-get install rar
sudo apt-get install original-awk
sudo apt-get install gawk
sudo apt-get install p7zip-full
sudo apt-get install gperf
sudo apt-get install libsdl1.2-dev
sudo apt-get install libesd0-dev
sudo apt-get install squashfs-tools
sudo apt-get install squashfs-tools
sudo apt-get install curl
sudo apt-get install libncurses5-dev
sudo apt-get install pngcrush
sudo apt-get install schedtool
sudo apt-get install mingw32
sudo apt-get install tofrodos
sudo apt-get install python-markdown
sudo apt-get install libxml2-utils
sudo apt-get install openjdk-6-jdk
sudo apt-get install g++-multilib
sudo apt-get install lib32z1-dev
sudo apt-get install ia32-libs
sudo apt-get install ib32ncurses5-dev
sudo apt-get install lib32readline-gplv2-dev
sudo apt-get install xsltproc
sudo apt-get install gnupg
sudo apt-get install flex
sudo apt-get install bison
sudo apt-get install libsdl1.2-dev
sudo apt-get install libesd0-dev
sudo apt-get install libwxgtk2.8-dev
sudo apt-get install squashfs-tools
sudo apt-get install build-essential
sudo apt-get install libncurses5-dev
sudo apt-get install zlib1g-dev
sudo apt-get install pngcrush
sudo apt-get install schedtool
sudo apt-get upgrade
